export {default as Students} from './Students' 
export {default as Employee} from './Employee' 
export {default as Product} from './Product' 
export {default as Profile} from './Profile' 
export {default as School} from './School' 